import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Digestion Supplements for Seniors | VitaTrack',
  alternates: { canonical: 'https://thevitatrack.com/digestion' },
};

export default function DigestionPage() {
  return (
    <>
      <style>{`
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}:root{--hdr:#14442A;--hero:#1E6B3E;--green:#1A5632;--green-hover:#134225;--bg:#F7F6F3;--white:#FFF;--border:#E8E6E1;--text:#2C2C2A;--text2:#555550;--muted:#717170;--badge:#E8F5E9;--shadow:0 4px 12px rgba(0,0,0,.08);--r:12px;--warn-bg:#FFF8E1;--warn-border:#FFE082;--warn-text:#6D4C00;--feat-bg:#FFFDF5;--feat-border:#E8D48B}html{scroll-behavior:smooth}body{font-family:'Source Sans 3',-apple-system,BlinkMacSystemFont,sans-serif;font-size:18px;line-height:1.6;color:var(--text);background:var(--bg);-webkit-font-smoothing:antialiased}
.hdr{background:var(--hdr);position:sticky;top:0;z-index:1000;border-bottom:1px solid rgba(255,255,255,.1)}.hdr-inner{max-width:1100px;margin:0 auto;padding:10px 20px;display:flex;align-items:center;justify-content:space-between}.hdr-logo{display:flex;align-items:center;gap:10px;text-decoration:none;color:#fff}.hdr-logo svg{width:32px;height:32px;flex-shrink:0}.hdr-logo span{font-size:22px;font-weight:700}.hdr-nav{display:flex;gap:6px}.hdr-nav a{color:rgba(255,255,255,.85);text-decoration:none;font-size:15px;font-weight:500;padding:8px 16px;border-radius:8px;transition:background .15s}.hdr-nav a:hover{background:rgba(255,255,255,.1);color:#fff}.hdr-toggle{display:none;background:none;border:none;color:#fff;cursor:pointer;padding:8px;min-height:44px;min-width:44px;align-items:center;justify-content:center}.hdr-toggle svg{width:26px;height:26px}.mob{display:none;position:fixed;inset:0;background:var(--hdr);z-index:9999;flex-direction:column;overflow-y:auto}.mob.open{display:flex}.mob-top{display:flex;align-items:center;justify-content:space-between;padding:10px 20px;border-bottom:1px solid rgba(255,255,255,.1)}.mob-logo{display:flex;align-items:center;gap:8px;color:#fff;text-decoration:none}.mob-logo svg{width:28px;height:28px}.mob-logo span{font-size:20px;font-weight:700}.mob-x{background:rgba(255,255,255,.1);border:none;color:#fff;width:44px;height:44px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:22px}.mob-links{display:flex;flex-direction:column;padding:8px 0}.mob-links a{color:#fff;text-decoration:none;font-size:18px;font-weight:500;padding:16px 28px;border-bottom:1px solid rgba(255,255,255,.1);transition:background .15s}.mob-links a:first-child{border-top:1px solid rgba(255,255,255,.1)}.mob-links a:hover{background:rgba(255,255,255,.08)}@media(max-width:768px){.hdr-nav{display:none}.hdr-toggle{display:flex}}
.page-hero{background:var(--hero);color:#fff;padding:36px 24px 32px}.page-hero-inner{max-width:800px;margin:0 auto}.breadcrumb{font-size:15px;color:rgba(255,255,255,.7);margin-bottom:12px}.breadcrumb a{color:rgba(255,255,255,.85);text-decoration:none}.page-hero h1{font-size:30px;font-weight:700;line-height:1.2;margin-bottom:10px}.page-hero p{font-size:18px;color:rgba(255,255,255,.9);max-width:600px}
.main-wrap{max-width:1100px;margin:0 auto;padding:0 20px;display:flex;gap:28px;align-items:flex-start}.main{flex:1;max-width:800px;min-width:0}.sidebar{width:240px;flex-shrink:0;position:sticky;top:70px;display:none}.sidebar-inner{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:18px}.sidebar h4{font-size:15px;font-weight:700;color:var(--text);margin-bottom:14px}.sb-links{display:flex;flex-direction:column;gap:6px}.sb-link{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:8px;text-decoration:none;background:#F8FAF8;transition:background .15s}.sb-link:hover{background:#E8F5E9}.sb-link.feat{background:#FFF8E8;border:1px solid #E8D48B}.sb-link.feat:hover{background:#FFF0C8}.sb-num{font-size:12px;width:22px;height:22px;background:var(--green);color:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;font-weight:700}.sb-link.feat .sb-num{background:#B8860B}.sb-name{font-size:14px;font-weight:600;color:var(--green);line-height:1.3}.sb-link.feat .sb-name{color:#7A5F00}.sb-divider{border:none;border-top:1px solid var(--border);margin:10px 0}.sb-cta{display:block;text-align:center;background:#B8860B;color:#fff;text-decoration:none;padding:10px;border-radius:8px;font-size:14px;font-weight:700;margin-top:12px;transition:background .15s}.sb-cta:hover{background:#956E08}@media(min-width:1000px){.sidebar{display:block}}@media(max-width:999px){.main-wrap{max-width:800px}}
.intro{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:24px;margin:28px 0;border-left:4px solid var(--green)}.intro h3{font-size:19px;font-weight:700;margin-bottom:8px;color:var(--green)}.intro p{font-size:16px;color:var(--text2);line-height:1.6}
.qp{background:#F0FAF3;border:2px solid var(--green);border-radius:var(--r);padding:22px 24px;margin:0 0 28px}.qp h3{font-size:19px;font-weight:700;color:var(--green);margin-bottom:10px}.qp p{font-size:16px;color:var(--text);line-height:1.6;margin-bottom:6px}.qp a{color:var(--green);font-weight:600}
.p-card{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:24px 22px;margin-bottom:18px;position:relative}.p-card.featured{border:2px solid var(--feat-border);background:var(--feat-bg)}.p-num{position:absolute;top:-11px;left:22px;width:30px;height:30px;background:var(--green);color:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700}.p-card.featured .p-num{background:#B8860B}.feat-tag{display:inline-block;background:#B8860B;color:#fff;font-size:13px;font-weight:700;padding:4px 12px;border-radius:20px;margin-bottom:10px}
.p-top{display:flex;gap:18px;align-items:flex-start;margin-bottom:14px}.p-img{width:90px;flex-shrink:0;background:#F8FAF8;border-radius:10px;padding:12px;text-align:center}.p-card.featured .p-img{background:#FFF8E8}.p-img svg{width:60px;height:auto}.p-info{flex:1}.p-name{font-size:21px;font-weight:700;color:var(--green);margin:4px 0 4px;line-height:1.2}.p-sub{font-size:15px;color:var(--text2);margin-bottom:10px}.p-pills{display:flex;gap:6px;flex-wrap:wrap}.p-pill{font-size:13px;background:var(--badge);color:var(--green);padding:4px 10px;border-radius:20px;font-weight:600}.p-card.featured .p-pill{background:#FFF0C8;color:#7A5F00}
.p-checks{display:flex;flex-direction:column;gap:8px;margin-bottom:16px}.p-chk{display:flex;align-items:flex-start;gap:9px}.p-chk .tick{color:var(--green);font-size:18px;flex-shrink:0;line-height:1.3}.p-chk span{font-size:16px;color:var(--text);line-height:1.45}
.p-badges{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:14px}.p-badge{font-size:13px;background:var(--badge);color:var(--green);padding:5px 12px;border-radius:20px;font-weight:600}
.p-tip{font-size:14px;color:var(--muted);margin-bottom:10px;line-height:1.5}.p-tip strong{color:var(--text2)}
.p-btn{display:flex;align-items:center;justify-content:center;gap:8px;background:var(--green);color:#fff;text-decoration:none;padding:15px 24px;border-radius:10px;font-size:18px;font-weight:700;min-height:54px;transition:background .15s;width:100%}.p-btn:hover{background:var(--green-hover)}.p-btn svg{width:18px;height:18px;flex-shrink:0}.p-card.featured .p-btn{background:#B8860B;font-size:19px;min-height:58px}.p-card.featured .p-btn:hover{background:#956E08}
.p-price{font-size:14px;color:var(--muted);text-align:center;margin-top:8px}
.faq{margin:36px 0}.faq h2{font-size:24px;font-weight:700;margin-bottom:20px;text-align:center}.faq-item{background:var(--white);border:1px solid var(--border);border-radius:var(--r);margin-bottom:10px;overflow:hidden}.faq-q{padding:16px 22px;font-size:18px;font-weight:600;color:var(--text);cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:12px;background:none;border:none;width:100%;text-align:left;font-family:inherit;line-height:1.4}.faq-q:hover{background:#FAFAF8}.faq-icon{font-size:22px;color:var(--muted);flex-shrink:0;transition:transform .2s}.faq-q.active .faq-icon{transform:rotate(45deg)}.faq-a{padding:0 22px 16px;font-size:16px;color:var(--text2);line-height:1.65;display:none}.faq-a.show{display:block}
.related{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:24px;margin:32px 0}.related h3{font-size:20px;font-weight:700;margin-bottom:16px}.r-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.r-link{display:flex;align-items:center;gap:10px;padding:14px 16px;border:1px solid var(--border);border-radius:10px;text-decoration:none;color:var(--green);font-weight:600;font-size:16px;transition:border-color .15s}.r-link:hover{border-color:#c5c3be;box-shadow:var(--shadow)}
.disc{background:#F5F4F1;border-radius:var(--r);padding:24px;margin:0 0 40px}.disc h4{font-size:16px;font-weight:700;margin-bottom:8px}.disc p{font-size:14px;color:var(--muted);line-height:1.7}.disc p+p{margin-top:8px}
.ftr{border-top:1px solid var(--border);background:linear-gradient(180deg,#FAFDFB,#F7F6F3);padding:36px 20px 20px;text-align:center}.ftr-inner{max-width:700px;margin:0 auto;display:flex;flex-direction:column;align-items:center;gap:20px}.ftr-brand{display:flex;flex-direction:column;align-items:center;gap:12px}.ftr-logo{display:inline-flex;align-items:center;gap:8px;text-decoration:none;color:var(--text)}.ftr-logo svg{width:22px;height:22px}.ftr-logo span{font-size:22px;font-weight:700}.ftr-logo:hover span{color:var(--green)}.ftr-social{display:flex;gap:10px;list-style:none}.ftr-social a{display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:#fff;border:1px solid var(--border);color:var(--green)}.ftr-social svg{width:18px;height:18px}.ftr-news{background:#FFF8EE;border:1px solid #F0E6D8;border-radius:14px;padding:18px 22px;width:100%;max-width:480px}.ftr-news h4{font-size:20px;font-weight:700;margin-bottom:10px}.ftr-form{display:flex;gap:8px;max-width:420px;margin:0 auto}.ftr-form input{flex:1;padding:12px 14px;border-radius:10px;border:1.5px solid var(--border);background:#fff;font:inherit;font-size:16px;min-width:0}.ftr-form button{padding:12px 20px;border-radius:10px;border:none;background:var(--green);color:#fff;font-weight:700;font-size:15px;cursor:pointer;min-height:48px;white-space:nowrap}.ftr-form button:hover{background:var(--green-hover)}.ftr-priv{margin-top:8px;font-size:14px;color:var(--muted)}.ftr-priv a{color:var(--green);text-decoration:underline}.ftr-links{display:flex;flex-wrap:wrap;justify-content:center;gap:4px 20px;list-style:none}.ftr-links a{display:inline-block;padding:8px 4px;text-decoration:none;color:var(--text);font-weight:600;font-size:15px;min-height:44px;border-bottom:2px solid transparent}.ftr-links a:hover{color:var(--green);border-color:var(--badge)}.ftr-btm{max-width:700px;margin:0 auto;padding:14px 20px 8px;text-align:center;border-top:1px dashed #E0DDD8}.ftr-btm p{margin:0 0 4px;color:var(--muted);font-size:14px}.ftr-btm a{color:var(--green);font-weight:700;text-decoration:none;font-size:15px}
@media(max-width:700px){.page-hero{padding:28px 20px 24px}.page-hero h1{font-size:25px}.p-card{padding:20px 18px}.p-name{font-size:19px}.p-img{width:80px;padding:10px}.p-img svg{width:52px}.r-grid{grid-template-columns:1fr}.ftr-form{flex-direction:column}.ftr-form button{width:100%}.faq-q{font-size:17px;padding:14px 18px}.faq-a{padding:0 18px 14px}}
      `}</style>
<header className="hdr"><div className="hdr-inner"><a href="/" className="hdr-logo"><svg viewBox="0 0 36 36" fill="none"><circle cx="18" cy="18" r="16" fill="#1A5632"/><path d="M18 28 L12.5 21.5 C10 18.5 10 15.5 12.5 13.5 C14.5 12 16.5 13 18 15.5 C19.5 13 21.5 12 23.5 13.5 C26 15.5 26 18.5 23.5 21.5Z" fill="#4ADE80" opacity=".85"/><path d="M13 20.5L16 20.5 17 17.5 18.5 23 20 19.5 23 19.5" fill="none" stroke="#fff" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg><span>VitaTrack</span></a><nav className="hdr-nav"><a href="/">Home</a><a href="/health-conditions/">Health Conditions</a><a href="/tools/">Health Tools</a></nav><button className="hdr-toggle" aria-label="Menu"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button></div></header>
<div id="m" className="mob"><div className="mob-top"><a href="/" className="mob-logo"><svg viewBox="0 0 36 36" fill="none"><circle cx="18" cy="18" r="16" fill="#1A5632"/><path d="M18 28 L12.5 21.5 C10 18.5 10 15.5 12.5 13.5 C14.5 12 16.5 13 18 15.5 C19.5 13 21.5 12 23.5 13.5 C26 15.5 26 18.5 23.5 21.5Z" fill="#4ADE80" opacity=".85"/><path d="M13 20.5L16 20.5 17 17.5 18.5 23 20 19.5 23 19.5" fill="none" stroke="#fff" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg><span>VitaTrack</span></a><button className="mob-x">✕</button></div><nav className="mob-links"><a href="/">Home</a><a href="/health-conditions/">Health Conditions</a><a href="/tools/">Health Tools</a><a href="/about/">About Us</a><a href="/contact/">Contact Us</a></nav></div>

<section className="page-hero"><div className="page-hero-inner">
<div className="breadcrumb"><a href="/">← All conditions</a></div>
<h1>6 Best Digestion &amp; Gut Supplements for Seniors</h1>
<p>Doctor-reviewed supplements for bloating, constipation, acid reflux, leaky gut, and digestive comfort after age 60.</p>
</div></section>

<div className="main-wrap">
<div className="main">

<div className="intro"><h3>A note about these recommendations</h3><p>Digestion naturally slows with age — your body produces less stomach acid, fewer enzymes, and your gut bacteria diversity declines. These supplements help restore what aging takes away. If you have chronic digestive issues, see a gastroenterologist for proper evaluation. Every product below is selected for safety and effectiveness in seniors.</p></div>

<div className="qp"><h3>⚡ Quick recommendation</h3>
<p><strong>If you try one thing:</strong> <a href="#primebiome">Our #1 Pick — PrimeBiome</a> is an all-in-one gut health formula.</p>
<p><strong>For bloating after meals:</strong> <a href="#enzymes">#3 Digestive Enzymes</a> — take right before eating.</p>
<p><strong>For constipation:</strong> <a href="#psyllium">#4 Psyllium Husk</a> + <a href="#probiotic">#2 Probiotic</a> together.</p>
</div>

<div className="p-card featured" id="primebiome"><div className="p-num">1</div>
<span className="feat-tag">⭐ Our #1 Pick</span>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="20" y="25" width="55" height="100" rx="8" fill="#B8860B"/><rect x="20" y="25" width="55" height="28" rx="8" fill="#956E08"/><rect x="30" y="10" width="35" height="18" rx="4" fill="#7A5F00"/><rect x="28" y="60" width="39" height="52" rx="4" fill="white" opacity=".95"/><text x="47" y="78" textAnchor="middle" fontFamily="sans-serif" fontSize="6" fontWeight="700" fill="#7A5F00">PRIME</text><text x="47" y="88" textAnchor="middle" fontFamily="sans-serif" fontSize="6" fontWeight="700" fill="#7A5F00">BIOME</text><text x="47" y="100" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fill="#956E08">Gut</text></svg></div>
<div className="p-info"><h2 className="p-name" style={{"color":"#7A5F00"}}>PrimeBiome — Complete Gut Health</h2><div className="p-sub">All-in-one formula to restore gut bacteria, improve digestion, and reduce bloating</div><div className="p-pills"><span className="p-pill">Daily capsule</span><span className="p-pill">With food</span><span className="p-pill">Results: 2-4 weeks</span></div></div></div>
<div className="p-checks">
<div className="p-chk"><span className="tick" style={{"color":"#B8860B"}}>✓</span><span>Combines probiotics, prebiotics, and digestive support in one convenient formula</span></div>
<div className="p-chk"><span className="tick" style={{"color":"#B8860B"}}>✓</span><span>Restores the gut bacteria diversity that declines significantly after age 60</span></div>
<div className="p-chk"><span className="tick" style={{"color":"#B8860B"}}>✓</span><span>Supports healthy digestion, reduced bloating, and regular bowel movements</span></div>
<div className="p-chk"><span className="tick" style={{"color":"#B8860B"}}>✓</span><span>No need to buy separate probiotic + prebiotic + enzyme supplements</span></div>
<div className="p-chk"><span className="tick" style={{"color":"#B8860B"}}>✓</span><span>Money-back guarantee — try it risk-free</span></div>
</div>
<div className="p-badges"><span className="p-badge" style={{"background":"#FFF0C8","color":"#7A5F00"}}>All-in-one gut formula</span><span className="p-badge" style={{"background":"#FFF0C8","color":"#7A5F00"}}>GMP certified</span><span className="p-badge" style={{"background":"#FFF0C8","color":"#7A5F00"}}>Money-back guarantee</span></div>
<a href="https://primebiome24.com/text.php#aff=healthyhabitat90" className="p-btn" target="_blank" rel="noopener noreferrer">Check Latest Price &amp; Availability <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Special discount available — check site for current pricing</div></div>

<div className="p-card" id="probiotic"><div className="p-num">2</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><circle cx="54" cy="80" r="3" fill="#4ADE80"/><circle cx="60" cy="78" r="3" fill="#34C76A"/><circle cx="66" cy="80" r="3" fill="#2DB85A"/><circle cx="57" cy="84" r="3" fill="#4ADE80" opacity=".6"/><circle cx="63" cy="84" r="3" fill="#34C76A" opacity=".6"/><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">PROBI</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">OTIC</text></svg></div>
<div className="p-info"><h2 className="p-name">Daily Probiotic (Multi-Strain)</h2><div className="p-sub">Replenishes the good bacteria your gut loses with age</div><div className="p-pills"><span className="p-pill">50 billion CFU</span><span className="p-pill">With food</span><span className="p-pill">2-4 weeks</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Your gut bacteria diversity drops 40%+ by age 60 — probiotics help restore it</span></div><div className="p-chk"><span className="tick">✓</span><span>Multi-strain with Lactobacillus + Bifidobacterium — the strains that decline most</span></div><div className="p-chk"><span className="tick">✓</span><span>Supports immune function — 70% of your immune system lives in your gut</span></div><div className="p-chk"><span className="tick">✓</span><span>Delayed-release capsules survive stomach acid — so bacteria actually reach your gut</span></div></div>
<div className="p-badges"><span className="p-badge">50 billion CFU</span><span className="p-badge">Delayed-release</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> Multi-strain (10+ strains), 50 billion CFU, delayed-release capsules, refrigerated or shelf-stable</div>
<a href="https://amzn.to/3PuqQmj" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $22–32 for a 1-month supply</div></div>

<div className="p-card" id="enzymes"><div className="p-num">3</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><path d="M54 80L58 76L62 80L66 76" stroke="#4ADE80" strokeWidth="2" fill="none" strokeLinecap="round"/><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">DIGEST</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">ENZYME</text></svg></div>
<div className="p-info"><h2 className="p-name">Digestive Enzyme Complex</h2><div className="p-sub">Replaces the enzymes your body stops making — reduces bloating after meals</div><div className="p-pills"><span className="p-pill">1 capsule per meal</span><span className="p-pill">Before eating</span><span className="p-pill">Immediate</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Your body produces 60-70% fewer digestive enzymes by age 70</span></div><div className="p-chk"><span className="tick">✓</span><span>Broad-spectrum: breaks down proteins, fats, carbs, and fiber</span></div><div className="p-chk"><span className="tick">✓</span><span>Take right before meals — works immediately to reduce bloating and gas</span></div><div className="p-chk"><span className="tick">✓</span><span>Helps your body absorb more nutrients from the food you eat</span></div></div>
<div className="p-badges"><span className="p-badge">Broad-spectrum</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> Broad-spectrum with protease, lipase, amylase, cellulase — take right before meals</div>
<a href="https://amzn.to/4swtZ3L" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $16–24 for a 1-month supply</div></div>

<div className="p-card" id="psyllium"><div className="p-num">4</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><path d="M50 82Q55 74 60 82Q65 74 70 82" stroke="#D4A843" strokeWidth="2" fill="none" strokeLinecap="round"/><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">PSYLL</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">IUM</text></svg></div>
<div className="p-info"><h2 className="p-name">Psyllium Husk Fiber</h2><div className="p-sub">The gentlest, most effective fiber for regularity and cholesterol</div><div className="p-pills"><span className="p-pill">5g daily</span><span className="p-pill">With 8oz water</span><span className="p-pill">1-3 days</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Absorbs water and adds bulk to stool — makes constipation relief gentle and predictable</span></div><div className="p-chk"><span className="tick">✓</span><span>FDA-approved to lower cholesterol — a bonus for heart health</span></div><div className="p-chk"><span className="tick">✓</span><span>Also feeds good gut bacteria (prebiotic) — supports your probiotic</span></div><div className="p-chk"><span className="tick">✓</span><span>Start with half dose and increase gradually — always drink plenty of water</span></div></div>
<div className="p-badges"><span className="p-badge">Organic</span><span className="p-badge">FDA-approved claim</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> Organic whole husk or powder — always take with at least 8oz water</div>
<a href="https://amzn.to/4bwwU6o" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $10–16 for a 2-month supply</div></div>

<div className="p-card" id="dgl"><div className="p-num">5</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><rect x="52" y="76" width="16" height="10" rx="3" fill="#8B4513" opacity=".5"/><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="6" fontWeight="700" fill="#1A5632">DGL</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fontWeight="700" fill="#1A5632">400mg</text></svg></div>
<div className="p-info"><h2 className="p-name">DGL Licorice</h2><div className="p-sub">Soothes stomach lining and acid reflux — without affecting blood pressure</div><div className="p-pills"><span className="p-pill">400mg</span><span className="p-pill">Before meals</span><span className="p-pill">2-4 weeks</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Coats and protects your stomach lining — soothes heartburn and acid reflux</span></div><div className="p-chk"><span className="tick">✓</span><span>DGL means the blood-pressure-raising compound is removed — safe for seniors</span></div><div className="p-chk"><span className="tick">✓</span><span>Natural alternative for people who want to reduce PPI (Prilosec/Nexium) use</span></div><div className="p-chk"><span className="tick">✓</span><span>Chewable tablets work best — chew 20 minutes before meals for coating effect</span></div></div>
<div className="p-badges"><span className="p-badge">Deglycyrrhizinated</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> "DGL" licorice (deglycyrrhizinated) — chewable tablets, 400mg, take before meals</div>
<a href="https://amzn.to/4rTvKqG" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $10–16 for a 2-month supply</div></div>

<div className="p-card" id="glutamine"><div className="p-num">6</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><text x="60" y="84" textAnchor="middle" fontFamily="sans-serif" fontSize="10" fontWeight="900" fill="#1A5632">L-G</text><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fontWeight="700" fill="#1A5632">GLUTA</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fontWeight="700" fill="#1A5632">MINE</text></svg></div>
<div className="p-info"><h2 className="p-name">L-Glutamine Powder</h2><div className="p-sub">The amino acid that repairs your gut lining from the inside out</div><div className="p-pills"><span className="p-pill">5g daily</span><span className="p-pill">Empty stomach</span><span className="p-pill">4-8 weeks</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Primary fuel source for the cells that line your intestinal wall</span></div><div className="p-chk"><span className="tick">✓</span><span>Helps repair and strengthen the gut barrier — reduces "leaky gut" permeability</span></div><div className="p-chk"><span className="tick">✓</span><span>Unflavored powder mixes into water — easy to take on an empty stomach</span></div><div className="p-chk"><span className="tick">✓</span><span>Especially important if you take NSAIDs which damage the gut lining over time</span></div></div>
<div className="p-badges"><span className="p-badge">Pure powder</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> Pure L-Glutamine powder, unflavored, 5g per scoop, no additives</div>
<a href="https://amzn.to/4lKoETI" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $14–20 for a 2-month supply</div></div>

<div className="faq"><h2>Frequently Asked Questions</h2>
<div className="faq-item"><button className="faq-q">What is the best probiotic for seniors?<span className="faq-icon">+</span></button><div className="faq-a">Look for a multi-strain probiotic with 30-50 billion CFU, including Lactobacillus and Bifidobacterium strains. Delayed-release capsules survive stomach acid better. Most notice improvement in bloating and regularity within 2-4 weeks.</div></div>
<div className="faq-item"><button className="faq-q">Why do I have more digestive problems as I age?<span className="faq-icon">+</span></button><div className="faq-a">After 60, your body produces less stomach acid, fewer digestive enzymes, and has less diverse gut bacteria. Medications like PPIs, antibiotics, and NSAIDs further disrupt digestion. This leads to bloating, constipation, and nutrient malabsorption.</div></div>
<div className="faq-item"><button className="faq-q">Should I take digestive enzymes?<span className="faq-icon">+</span></button><div className="faq-a">Yes if you experience bloating, gas, or heaviness after meals. Your body produces 60-70% fewer digestive enzymes by age 70. A broad-spectrum enzyme supplement helps break down food so your body absorbs nutrients properly.</div></div>
<div className="faq-item"><button className="faq-q">Is psyllium husk good for constipation?<span className="faq-icon">+</span></button><div className="faq-a">Yes — psyllium is one of the most effective and gentle fiber supplements. It absorbs water and adds bulk to stool. Start with a small dose and increase gradually. Always drink at least 8oz of water with each dose.</div></div>
<div className="faq-item"><button className="faq-q">Can gut health affect my immune system?<span className="faq-icon">+</span></button><div className="faq-a">Absolutely — about 70% of your immune system lives in your gut. A healthy gut microbiome supports immune function, reduces inflammation, and even affects mood. Probiotics and prebiotic fiber are the two most important supplements for gut immune support.</div></div>
</div>

<div className="related"><h3>Related Health Conditions</h3><div className="r-grid">
<a href="/liver/" className="r-link"><span>🫀</span> Liver &amp; detox</a>
<a href="/longevity/" className="r-link"><span>🧬</span> Longevity</a>
<a href="/kidney/" className="r-link"><span>💧</span> Kidney health</a>
<a href="/heart/" className="r-link"><span>❤️</span> Heart health</a>
</div></div>

<div className="disc"><h4>Medical &amp; Affiliate Disclosure</h4>
<p>This page is for educational purposes only and is not medical advice. If you have chronic digestive issues, see a gastroenterologist. Always consult your doctor before starting any supplement.</p>
<p>VitaTrack may earn a commission from purchases through links on this page. This does not affect our recommendations.</p></div>

</div>

<aside className="sidebar"><div className="sidebar-inner">
<h4>Quick navigation</h4>
<div className="sb-links">
<a href="#primebiome" className="sb-link feat"><span className="sb-num">1</span><span className="sb-name">PrimeBiome</span></a>
<a href="#probiotic" className="sb-link"><span className="sb-num">2</span><span className="sb-name">Daily Probiotic</span></a>
<a href="#enzymes" className="sb-link"><span className="sb-num">3</span><span className="sb-name">Digestive Enzymes</span></a>
<a href="#psyllium" className="sb-link"><span className="sb-num">4</span><span className="sb-name">Psyllium Husk</span></a>
<a href="#dgl" className="sb-link"><span className="sb-num">5</span><span className="sb-name">DGL Licorice</span></a>
<a href="#glutamine" className="sb-link"><span className="sb-num">6</span><span className="sb-name">L-Glutamine</span></a>
</div>
<hr className="sb-divider" />
<a href="#primebiome" className="sb-cta">Check #1 Pick →</a>
</div></aside>
</div>

<footer className="ftr"><div className="ftr-inner"><div className="ftr-brand"><a href="/" className="ftr-logo"><svg viewBox="0 0 28 28" fill="none"><circle cx="14" cy="14" r="13" fill="#1A5632" opacity=".14"/><path d="M7 16.5l4 4L21 9.5" fill="none" stroke="#1A5632" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/></svg><span>TheVitatrack</span></a><ul className="ftr-social"><li><a href="https://www.facebook.com/profile.php?id=61550903702285" target="_blank" aria-label="Facebook"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M22 12.07C22 6.48 17.52 2 11.93 2S2 6.48 2 12.07c0 5 3.66 9.14 8.44 9.93v-7.03H8.08v-2.9h2.36V9.41c0-2.33 1.38-3.62 3.5-3.62.99 0 2.02.18 2.02.18v2.23h-1.14c-1.12 0-1.47.7-1.47 1.42v1.7h2.5l-.4 2.9h-2.1V22c4.78-.79 8.44-4.93 8.44-9.93z"/></svg></a></li><li><a href="https://www.youtube.com/@healthyhabitat1304" target="_blank" aria-label="YouTube"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M23.5 6.2a3.1 3.1 0 0 0-2.2-2.2C19.3 3.5 12 3.5 12 3.5s-7.3 0-9.3.5A3.1 3.1 0 0 0 .5 6.2C0 8.3 0 12 0 12s0 3.7.5 5.8a3.1 3.1 0 0 0 2.2 2.2c2 .5 9.3.5 9.3.5s7.3 0 9.3-.5a3.1 3.1 0 0 0 2.2-2.2c.5-2.1.5-5.8.5-5.8s0-3.7-.5-5.8zM9.6 15.6V8.4L15.8 12l-6.2 3.6z"/></svg></a></li></ul></div>
<div className="ftr-news"><h4>Get our wellness newsletter</h4><form className="ftr-form" action="/subscribe" method="post"><input name="email" type="email" placeholder="Enter your email" required /><button type="submit">SIGN UP</button></form><p className="ftr-priv">Your <a href="/privacy-policy/">privacy</a> is important to us</p></div>
<ul className="ftr-links"><li><a href="/about/">About Us</a></li><li><a href="/contact/">Contact Us</a></li><li><a href="/privacy-policy/">Privacy Policy</a></li><li><a href="/terms-of-use/">Terms of Use</a></li><li><a href="/sitemap/">Sitemap</a></li><li><a href="/health-conditions/">Health Conditions</a></li><li><a href="/tools/">Health Tools</a></li></ul>
</div><div className="ftr-btm"><p>&copy; 2026 TheVitatrack. Educational content only &mdash; not a substitute for professional advice.</p><p>As an Amazon Associate, VitaTrack earns from qualifying purchases.</p></div></footer>

      <section style={{maxWidth:"840px",margin:"48px auto 60px",padding:"0 20px"}}>
        <div style={{borderTop:"2px solid #E8E6E1",paddingTop:"32px"}}>
          <h2 style={{color:"#14442A",fontSize:"1.4rem",fontWeight:700,marginBottom:"20px"}}>Related Health Guides</h2>
          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))",gap:"4px"}}>
          <Link href="/conditions/constipation" style={{color:"#1A5632",display:"block",padding:"8px 0",textDecoration:"none",fontWeight:500,borderBottom:"1px solid #E8E6E1"}}>Constipation</Link>
          <Link href="/conditions/gerd-acid-reflux" style={{color:"#1A5632",display:"block",padding:"8px 0",textDecoration:"none",fontWeight:500,borderBottom:"1px solid #E8E6E1"}}>GERD & Acid Reflux</Link>
          <Link href="/conditions/irritable-bowel-syndrome-ibs" style={{color:"#1A5632",display:"block",padding:"8px 0",textDecoration:"none",fontWeight:500,borderBottom:"1px solid #E8E6E1"}}>Irritable Bowel Syndrome</Link>
          <Link href="/conditions/malnutrition-unintended-weight-loss" style={{color:"#1A5632",display:"block",padding:"8px 0",textDecoration:"none",fontWeight:500,borderBottom:"1px solid #E8E6E1"}}>Malnutrition & Weight Loss</Link>
          <Link href="/conditions/diabetes-type-2" style={{color:"#1A5632",display:"block",padding:"8px 0",textDecoration:"none",fontWeight:500,borderBottom:"1px solid #E8E6E1"}}>Type 2 Diabetes</Link>
          </div>
        </div>
      </section>
    </>
  );
}
