import Link from 'next/link';
import Header from '@/components/Header';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Premium Senior Health Guides | VitaTrack',
  alternates: { canonical: 'https://thevitatrack.com/guides' },
};

export default function GuidesPage() {
  return (
    <>
      <Header />
      <style>{`
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}
:root{--hdr:#14442A;--hero:#1E6B3E;--green:#1A5632;--bg:#F7F6F3;--cream:#FDFAF5;--white:#fff;--border:#E8E6E1;--text:#2C2C2A;--text2:#555550;--muted:#717170;--radius:14px}
html{scroll-behavior:smooth}body{font-family:'Source Sans 3',-apple-system,sans-serif;font-size:18px;line-height:1.6;color:var(--text);background:var(--bg)}
.hdr{background:var(--hdr);position:sticky;top:0;z-index:1000}.hdr-inner{max-width:1100px;margin:0 auto;padding:10px 20px;display:flex;align-items:center;justify-content:space-between}.hdr-logo{display:flex;align-items:center;gap:10px;text-decoration:none;color:#fff}.hdr-logo svg{width:32px;height:32px}.hdr-logo span{font-size:22px;font-weight:700}.hdr-nav{display:flex;gap:6px}.hdr-nav a{color:rgba(255,255,255,.85);text-decoration:none;font-size:15px;font-weight:500;padding:8px 16px;border-radius:8px;transition:background .15s}.hdr-nav a:hover,.hdr-nav a.active{background:rgba(255,255,255,.12);color:#fff}.hdr-toggle{display:none;background:none;border:none;color:#fff;cursor:pointer;padding:8px;min-height:44px;min-width:44px}
.hero{background:linear-gradient(160deg,#0f3320,#1a5632 40%,#1E6B3E);color:#fff;padding:72px 20px 64px;text-align:center}.hero-ey{font-family:'Fraunces',serif;font-size:13px;letter-spacing:2.5px;text-transform:uppercase;opacity:.55;margin-bottom:14px}.hero h1{font-family:'Fraunces',serif;font-size:clamp(30px,5.5vw,52px);font-weight:800;line-height:1.1;max-width:680px;margin:0 auto 18px}.hero h1 em{font-style:italic;color:#86efac}.hero-sub{font-size:19px;max-width:540px;margin:0 auto;opacity:.85;line-height:1.5}
.book-wrap{perspective:600px;display:inline-block}.book{width:160px;height:220px;position:relative;transform-style:preserve-3d;transform:rotateY(-18deg);transition:transform .5s;cursor:pointer}.book:hover{transform:rotateY(-30deg)}.book-front{position:absolute;inset:0;border-radius:0 3px 3px 0;display:flex;flex-direction:column;justify-content:space-between;padding:18px 14px 14px;color:#fff;z-index:2;backface-visibility:hidden;overflow:hidden}.book-front::after{content:'';position:absolute;top:0;left:0;width:100%;height:100%;background:linear-gradient(105deg,rgba(255,255,255,0) 30%,rgba(255,255,255,.08) 45%,rgba(255,255,255,0) 50%);pointer-events:none}.book-spine{position:absolute;top:0;left:0;width:18px;height:100%;transform:rotateY(90deg) translateX(-9px) translateZ(9px);border-radius:3px 0 0 3px}.book-pages{position:absolute;top:2px;right:0;width:16px;height:calc(100% - 4px);background:linear-gradient(90deg,#f5f0e8,#fff,#f5f0e8);transform:translateX(7px) translateZ(-1px);border-radius:0 2px 2px 0;border:1px solid #e0ddd5}.book-shadow{position:absolute;bottom:-8px;left:10%;width:80%;height:12px;background:rgba(0,0,0,.15);filter:blur(8px);border-radius:50%;transition:all .5s}.book:hover .book-shadow{width:90%;left:5%;background:rgba(0,0,0,.2)}.bf-icon{font-size:32px;line-height:1}.bf-title{font-family:'Fraunces',serif;font-size:13px;font-weight:700;line-height:1.25}.bf-bottom{display:flex;justify-content:space-between;align-items:flex-end;font-size:9px;text-transform:uppercase;letter-spacing:.5px;opacity:.75}.bf-brand{font-weight:700}
.prod{background:var(--white);border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;text-decoration:none;color:var(--text);transition:transform .25s,box-shadow .25s;display:flex;flex-direction:column}.prod:hover{transform:translateY(-4px);box-shadow:0 12px 32px rgba(0,0,0,.08)}.prod-top{padding:28px 20px 20px;display:flex;justify-content:center;background:var(--cream)}.prod-body{padding:18px 20px 14px;flex:1;display:flex;flex-direction:column}.prod-title{font-family:'Fraunces',serif;font-size:17px;font-weight:700;line-height:1.3;margin-bottom:6px}.prod-desc{font-size:14px;color:var(--text2);line-height:1.5;flex:1;margin-bottom:12px}.prod-meta{display:flex;justify-content:space-between;align-items:center;font-size:13px;color:var(--muted)}.prod-price{font-family:'Fraunces',serif;font-size:22px;font-weight:800;color:var(--green)}.prod-footer{padding:0 20px 18px}.btn-v{display:block;text-align:center;padding:11px;border:1.5px solid var(--green);border-radius:10px;color:var(--green);font-weight:700;font-size:14px;text-decoration:none;transition:all .2s}.btn-v:hover{background:var(--green);color:#fff}
.main{max-width:1060px;margin:0 auto;padding:0 20px}.sh{margin:60px 0 24px;text-align:center}.sh h2{font-family:'Fraunces',serif;font-size:28px;font-weight:800;margin-bottom:6px}.sh p{font-size:16px;color:var(--text2);max-width:480px;margin:0 auto}.pgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:20px}
.bundle{max-width:940px;margin:-36px auto 0;padding:0 20px;position:relative;z-index:10}.bc{background:var(--white);border:2px solid var(--green);border-radius:20px;padding:36px;display:flex;gap:36px;align-items:center;box-shadow:0 12px 40px rgba(0,0,0,.1)}.bc-books{display:flex;flex-shrink:0}.bc-books .book-wrap{margin-left:-20px}.bc-books .book-wrap:first-child{margin-left:0}.bc-info{flex:1}.bc-info h2{font-family:'Fraunces',serif;font-size:26px;font-weight:800;margin-bottom:10px}.bc-info p{font-size:15px;color:var(--text2);margin-bottom:14px;line-height:1.5}.bc-pr{display:flex;align-items:baseline;gap:12px;margin-bottom:16px}.bc-was{font-size:16px;color:var(--muted);text-decoration:line-through}.bc-now{font-family:'Fraunces',serif;font-size:44px;font-weight:800;color:var(--green)}.bc-save{background:#fef3c7;color:#92400e;font-size:12px;font-weight:700;padding:4px 10px;border-radius:100px}.btn-buy{display:inline-block;background:var(--green);color:#fff;font-weight:700;font-size:16px;padding:14px 36px;border-radius:100px;text-decoration:none;transition:transform .2s,box-shadow .2s}.btn-buy:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(26,86,50,.3)}
.trust{margin:56px 0 0;padding:40px 0;border-top:1px solid var(--border);border-bottom:1px solid var(--border)}.tg{display:grid;grid-template-columns:repeat(4,1fr);gap:20px;max-width:860px;margin:0 auto;text-align:center}.ti svg{width:26px;height:26px;stroke:var(--green);fill:none;margin-bottom:6px}.ti-l{font-size:15px;font-weight:600}.ti-s{font-size:13px;color:var(--muted)}
.faq{max-width:680px;margin:48px auto 0}.faq h2{font-family:'Fraunces',serif;font-size:24px;font-weight:800;text-align:center;margin-bottom:20px}.fi{border-bottom:1px solid var(--border);padding:16px 0}.fq{font-weight:700;font-size:16px;cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:12px}.fq svg{width:18px;height:18px;stroke:var(--muted);fill:none;flex-shrink:0;transition:transform .2s}.fi.open .fq svg{transform:rotate(45deg)}.fa{font-size:15px;color:var(--text2);line-height:1.6;max-height:0;overflow:hidden;transition:max-height .3s}.fi.open .fa{max-height:300px;padding-top:8px}
.bcta{margin:52px 0;background:var(--green);border-radius:20px;padding:44px 28px;text-align:center;color:#fff}.bcta h3{font-family:'Fraunces',serif;font-size:26px;font-weight:800;margin-bottom:8px}.bcta p{font-size:16px;opacity:.85;max-width:480px;margin:0 auto 20px}.btn-w{display:inline-block;background:#fff;color:var(--green);font-weight:700;font-size:16px;padding:14px 36px;border-radius:100px;text-decoration:none;transition:transform .2s}.btn-w:hover{transform:translateY(-2px);box-shadow:0 8px 24px rgba(0,0,0,.2)}
.ftr{background:var(--white);padding:32px 20px;border-top:1px solid var(--border);text-align:center;margin-top:40px}.ftr p{font-size:14px;color:var(--muted);margin:3px 0}.ftr a{color:var(--green);text-decoration:none;font-weight:600}
@media(max-width:768px){.hdr-nav{display:none}.hdr-toggle{display:flex;align-items:center;justify-content:center}.hero{padding:52px 16px 44px}.bundle{margin-top:-20px;padding:0 12px}.bc{flex-direction:column;padding:24px 20px;gap:20px}.bc-books{justify-content:center}.book{width:120px;height:165px}.bf-title{font-size:11px}.bf-icon{font-size:24px}.pgrid{grid-template-columns:1fr}.tg{grid-template-columns:1fr 1fr}.bcta{padding:32px 16px}.main{padding:0 16px}}
.mob{display:none;position:fixed;inset:0;background:#14442A;z-index:9999;flex-direction:column;overflow-y:auto}.mob.open{display:flex}.mob-top{display:flex;align-items:center;justify-content:space-between;padding:10px 20px;border-bottom:1px solid rgba(255,255,255,.2)}.mob-logo{display:flex;align-items:center;gap:8px;color:#fff;text-decoration:none}.mob-logo svg{width:28px;height:28px}.mob-logo span{font-size:20px;font-weight:700}.mob-x{background:rgba(255,255,255,.1);border:none;color:#fff;width:44px;height:44px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:22px}.mob-links{display:flex;flex-direction:column;padding:8px 0}.mob-links a{color:#fff;text-decoration:none;font-size:18px;font-weight:500;padding:16px 28px;display:block;border-bottom:1px solid rgba(255,255,255,.2)}.mob-links a:first-child{border-top:1px solid rgba(255,255,255,.2)}.mob-links a:hover{background:rgba(255,255,255,.08)}
      `}</style>


<section className="hero"><div className="hero-ey">VitaTrack Premium Guides</div><h1>The Health Protocols Your <em>Doctor Doesn't Have Time</em> to Explain</h1><p className="hero-sub">Complete supplement protocols, drug interactions, diet plans, and tracking sheets for adults 60+.</p></section>
<div className="bundle"><div className="bc"><div className="bc-books">
<div className="book-wrap"><div className="book"><div className="book-front" style={{"padding":"0","overflow":"hidden","background":"none"}}><img src="/assets/covers/heart-bp-protocol.webp" alt="Heart After 60" style={{"width":"100%","height":"100%","objectFit":"cover","borderRadius":"0 3px 3px 0"}} loading="lazy" /></div><div className="book-spine" style={{"background":"#7f1d1d"}}></div><div className="book-pages"></div><div className="book-shadow"></div></div></div>
<div className="book-wrap"><div className="book"><div className="book-front" style={{"padding":"0","overflow":"hidden","background":"none"}}><img src="/assets/covers/prostate-protocol.webp" alt="Prostate Fix" style={{"width":"100%","height":"100%","objectFit":"cover","borderRadius":"0 3px 3px 0"}} loading="lazy" /></div><div className="book-spine" style={{"background":"#1e3a5f"}}></div><div className="book-pages"></div><div className="book-shadow"></div></div></div>
<div className="book-wrap"><div className="book"><div className="book-front" style={{"padding":"0","overflow":"hidden","background":"none"}}><img src="/assets/covers/supplement-blueprint.webp" alt="Supplement Stack" style={{"width":"100%","height":"100%","objectFit":"cover","borderRadius":"0 3px 3px 0"}} loading="lazy" /></div><div className="book-spine" style={{"background":"#0f3320"}}></div><div className="book-pages"></div><div className="book-shadow"></div></div></div>
</div><div className="bc-info"><h2>The Complete Senior Health Vault</h2><p>Every guide we publish. Every protocol. Every tracking sheet. 19 premium guides, one purchase, lifetime access including future updates.</p><div className="bc-pr"><span className="bc-was">$190</span><span className="bc-now">$47</span><span className="bc-save">Save 75%</span></div><a href="https://payhip.com/b/5LPT1" target="_blank" className="btn-buy">Get All 19 Guides &rarr;</a></div></div></div>
<div className="main">
<div className="sh"><h2>Condition Protocol Guides</h2><p>Complete supplement, diet, and monitoring protocols by condition</p></div>
<div className="pgrid">
</div>
<div className="sh"><h2>Lifestyle &amp; Wellness Guides</h2><p>Diet plans, exercise, sleep, mood, and daily wellness systems</p></div>
<div className="pgrid">
</div>
<div className="trust"><div className="tg">
<div className="ti"><svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg><div className="ti-l">Evidence-based</div><div className="ti-s">Cites clinical research</div></div>
<div className="ti"><svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><path d="M14 2v6h6"/></svg><div className="ti-l">3,500-5,000+ words</div><div className="ti-s">Complete protocols</div></div>
<div className="ti"><svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" y1="22" x2="4" y2="15"/></svg><div className="ti-l">Senior-specific</div><div className="ti-s">Age-adjusted dosing</div></div>
<div className="ti"><svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg><div className="ti-l">Instant download</div><div className="ti-s">PDF, print-friendly</div></div>
</div></div>
<div className="faq"><h2>Common Questions</h2>
<div className="fi"><div className="fq">What format are the guides in?<svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg></div><div className="fa">All guides are delivered as downloadable PDF files readable on any device or printable at home. Senior-friendly fonts and clear formatting.</div></div>
<div className="fi"><div className="fq">Are these medical advice?<svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg></div><div className="fa">No. Educational resources based on published research. They help you have informed conversations with your doctor.</div></div>
<div className="fi"><div className="fq">Do you offer refunds?<svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg></div><div className="fa">Yes. 30-day money-back guarantee, no questions asked.</div></div>
<div className="fi"><div className="fq">Why not just use free info online?<svg viewBox="0 0 24 24" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg></div><div className="fa">Free articles give fragments across 20 websites. Our guides give the complete protocol in one place: exact dosages, timing, drug interactions, diet plans, and tracking sheets. No ads, no conflicting information.</div></div>
</div>
<div className="bcta"><h3>Get Everything for $47</h3><p>All 19 guides. Every protocol. Every tracking sheet. Lifetime access including future updates.</p><a href="https://payhip.com/b/5LPT1" target="_blank" className="btn-w">Get The Complete Vault &rarr;</a></div>
</div>

      

    </>
  );
}
