import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Skin and Hair Supplements for Seniors | VitaTrack',
  alternates: { canonical: 'https://thevitatrack.com/skin-hair' },
};

export default function SkinHairPage() {
  return (
    <>
      <style>{`
*,*::before,*::after{margin:0;padding:0;box-sizing:border-box}:root{--hdr:#14442A;--hero:#1E6B3E;--green:#1A5632;--green-hover:#134225;--bg:#F7F6F3;--white:#FFF;--border:#E8E6E1;--text:#2C2C2A;--text2:#555550;--muted:#717170;--badge:#E8F5E9;--shadow:0 4px 12px rgba(0,0,0,.08);--r:12px}html{scroll-behavior:smooth}body{font-family:'Source Sans 3',-apple-system,BlinkMacSystemFont,sans-serif;font-size:18px;line-height:1.6;color:var(--text);background:var(--bg);-webkit-font-smoothing:antialiased}
.hdr{background:var(--hdr);position:sticky;top:0;z-index:1000;border-bottom:1px solid rgba(255,255,255,.1)}.hdr-inner{max-width:1100px;margin:0 auto;padding:10px 20px;display:flex;align-items:center;justify-content:space-between}.hdr-logo{display:flex;align-items:center;gap:10px;text-decoration:none;color:#fff}.hdr-logo svg{width:32px;height:32px;flex-shrink:0}.hdr-logo span{font-size:22px;font-weight:700}.hdr-nav{display:flex;gap:6px}.hdr-nav a{color:rgba(255,255,255,.85);text-decoration:none;font-size:15px;font-weight:500;padding:8px 16px;border-radius:8px;transition:background .15s}.hdr-nav a:hover{background:rgba(255,255,255,.1);color:#fff}.hdr-toggle{display:none;background:none;border:none;color:#fff;cursor:pointer;padding:8px;min-height:44px;min-width:44px;align-items:center;justify-content:center}.hdr-toggle svg{width:26px;height:26px}.mob{display:none;position:fixed;inset:0;background:var(--hdr);z-index:9999;flex-direction:column;overflow-y:auto}.mob.open{display:flex}.mob-top{display:flex;align-items:center;justify-content:space-between;padding:10px 20px;border-bottom:1px solid rgba(255,255,255,.1)}.mob-logo{display:flex;align-items:center;gap:8px;color:#fff;text-decoration:none}.mob-logo svg{width:28px;height:28px}.mob-logo span{font-size:20px;font-weight:700}.mob-x{background:rgba(255,255,255,.1);border:none;color:#fff;width:44px;height:44px;border-radius:50%;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:22px}.mob-links{display:flex;flex-direction:column;padding:8px 0}.mob-links a{color:#fff;text-decoration:none;font-size:18px;font-weight:500;padding:16px 28px;border-bottom:1px solid rgba(255,255,255,.1)}.mob-links a:first-child{border-top:1px solid rgba(255,255,255,.1)}.mob-links a:hover{background:rgba(255,255,255,.08)}@media(max-width:768px){.hdr-nav{display:none}.hdr-toggle{display:flex}}
.page-hero{background:var(--hero);color:#fff;padding:36px 24px 32px}.page-hero-inner{max-width:800px;margin:0 auto}.breadcrumb{font-size:15px;color:rgba(255,255,255,.7);margin-bottom:12px}.breadcrumb a{color:rgba(255,255,255,.85);text-decoration:none}.page-hero h1{font-size:30px;font-weight:700;line-height:1.2;margin-bottom:10px}.page-hero p{font-size:18px;color:rgba(255,255,255,.9);max-width:600px}
.main-wrap{max-width:1100px;margin:0 auto;padding:0 20px;display:flex;gap:28px;align-items:flex-start}.main{flex:1;max-width:800px;min-width:0}.sidebar{width:240px;flex-shrink:0;position:sticky;top:70px;display:none}.sidebar-inner{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:18px}.sidebar h4{font-size:15px;font-weight:700;color:var(--text);margin-bottom:14px}.sb-links{display:flex;flex-direction:column;gap:6px}.sb-link{display:flex;align-items:center;gap:9px;padding:9px 10px;border-radius:8px;text-decoration:none;background:#F8FAF8;transition:background .15s}.sb-link:hover{background:#E8F5E9}.sb-num{font-size:12px;width:22px;height:22px;background:var(--green);color:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;flex-shrink:0;font-weight:700}.sb-name{font-size:14px;font-weight:600;color:var(--green);line-height:1.3}.sb-divider{border:none;border-top:1px solid var(--border);margin:10px 0}.sb-cta{display:block;text-align:center;background:var(--green);color:#fff;text-decoration:none;padding:10px;border-radius:8px;font-size:14px;font-weight:700;margin-top:12px;transition:background .15s}.sb-cta:hover{background:var(--green-hover)}@media(min-width:1000px){.sidebar{display:block}}@media(max-width:999px){.main-wrap{max-width:800px}}
.intro{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:24px;margin:28px 0;border-left:4px solid var(--green)}.intro h3{font-size:19px;font-weight:700;margin-bottom:8px;color:var(--green)}.intro p{font-size:16px;color:var(--text2);line-height:1.6}
.qp{background:#F0FAF3;border:2px solid var(--green);border-radius:var(--r);padding:22px 24px;margin:0 0 28px}.qp h3{font-size:19px;font-weight:700;color:var(--green);margin-bottom:10px}.qp p{font-size:16px;color:var(--text);line-height:1.6;margin-bottom:6px}.qp a{color:var(--green);font-weight:600}
.p-card{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:24px 22px;margin-bottom:18px;position:relative}.p-num{position:absolute;top:-11px;left:22px;width:30px;height:30px;background:var(--green);color:#fff;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:14px;font-weight:700}
.p-top{display:flex;gap:18px;align-items:flex-start;margin-bottom:14px}.p-img{width:90px;flex-shrink:0;background:#F8FAF8;border-radius:10px;padding:12px;text-align:center}.p-img svg{width:60px;height:auto}.p-info{flex:1}.p-name{font-size:21px;font-weight:700;color:var(--green);margin:4px 0 4px;line-height:1.2}.p-sub{font-size:15px;color:var(--text2);margin-bottom:10px}.p-pills{display:flex;gap:6px;flex-wrap:wrap}.p-pill{font-size:13px;background:var(--badge);color:var(--green);padding:4px 10px;border-radius:20px;font-weight:600}
.p-checks{display:flex;flex-direction:column;gap:8px;margin-bottom:16px}.p-chk{display:flex;align-items:flex-start;gap:9px}.p-chk .tick{color:var(--green);font-size:18px;flex-shrink:0;line-height:1.3}.p-chk span{font-size:16px;color:var(--text);line-height:1.45}
.p-badges{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:14px}.p-badge{font-size:13px;background:var(--badge);color:var(--green);padding:5px 12px;border-radius:20px;font-weight:600}
.p-tip{font-size:14px;color:var(--muted);margin-bottom:10px;line-height:1.5}.p-tip strong{color:var(--text2)}
.p-btn{display:flex;align-items:center;justify-content:center;gap:8px;background:var(--green);color:#fff;text-decoration:none;padding:15px 24px;border-radius:10px;font-size:18px;font-weight:700;min-height:54px;transition:background .15s;width:100%}.p-btn:hover{background:var(--green-hover)}.p-btn svg{width:18px;height:18px;flex-shrink:0}
.p-price{font-size:14px;color:var(--muted);text-align:center;margin-top:8px}
.faq{margin:36px 0}.faq h2{font-size:24px;font-weight:700;margin-bottom:20px;text-align:center}.faq-item{background:var(--white);border:1px solid var(--border);border-radius:var(--r);margin-bottom:10px;overflow:hidden}.faq-q{padding:16px 22px;font-size:18px;font-weight:600;color:var(--text);cursor:pointer;display:flex;justify-content:space-between;align-items:center;gap:12px;background:none;border:none;width:100%;text-align:left;font-family:inherit;line-height:1.4}.faq-q:hover{background:#FAFAF8}.faq-icon{font-size:22px;color:var(--muted);flex-shrink:0;transition:transform .2s}.faq-q.active .faq-icon{transform:rotate(45deg)}.faq-a{padding:0 22px 16px;font-size:16px;color:var(--text2);line-height:1.65;display:none}.faq-a.show{display:block}
.related{background:var(--white);border:1px solid var(--border);border-radius:var(--r);padding:24px;margin:32px 0}.related h3{font-size:20px;font-weight:700;margin-bottom:16px}.r-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.r-link{display:flex;align-items:center;gap:10px;padding:14px 16px;border:1px solid var(--border);border-radius:10px;text-decoration:none;color:var(--green);font-weight:600;font-size:16px;transition:border-color .15s}.r-link:hover{border-color:#c5c3be;box-shadow:var(--shadow)}
.disc{background:#F5F4F1;border-radius:var(--r);padding:24px;margin:0 0 40px}.disc h4{font-size:16px;font-weight:700;margin-bottom:8px}.disc p{font-size:14px;color:var(--muted);line-height:1.7}.disc p+p{margin-top:8px}
.ftr{border-top:1px solid var(--border);background:linear-gradient(180deg,#FAFDFB,#F7F6F3);padding:36px 20px 20px;text-align:center}.ftr-inner{max-width:700px;margin:0 auto;display:flex;flex-direction:column;align-items:center;gap:20px}.ftr-brand{display:flex;flex-direction:column;align-items:center;gap:12px}.ftr-logo{display:inline-flex;align-items:center;gap:8px;text-decoration:none;color:var(--text)}.ftr-logo svg{width:22px;height:22px}.ftr-logo span{font-size:22px;font-weight:700}.ftr-logo:hover span{color:var(--green)}.ftr-social{display:flex;gap:10px;list-style:none}.ftr-social a{display:grid;place-items:center;width:40px;height:40px;border-radius:50%;background:#fff;border:1px solid var(--border);color:var(--green)}.ftr-social svg{width:18px;height:18px}.ftr-news{background:#FFF8EE;border:1px solid #F0E6D8;border-radius:14px;padding:18px 22px;width:100%;max-width:480px}.ftr-news h4{font-size:20px;font-weight:700;margin-bottom:10px}.ftr-form{display:flex;gap:8px;max-width:420px;margin:0 auto}.ftr-form input{flex:1;padding:12px 14px;border-radius:10px;border:1.5px solid var(--border);background:#fff;font:inherit;font-size:16px;min-width:0}.ftr-form button{padding:12px 20px;border-radius:10px;border:none;background:var(--green);color:#fff;font-weight:700;font-size:15px;cursor:pointer;min-height:48px;white-space:nowrap}.ftr-form button:hover{background:var(--green-hover)}.ftr-priv{margin-top:8px;font-size:14px;color:var(--muted)}.ftr-priv a{color:var(--green);text-decoration:underline}.ftr-links{display:flex;flex-wrap:wrap;justify-content:center;gap:4px 20px;list-style:none}.ftr-links a{display:inline-block;padding:8px 4px;text-decoration:none;color:var(--text);font-weight:600;font-size:15px;min-height:44px;border-bottom:2px solid transparent}.ftr-links a:hover{color:var(--green);border-color:var(--badge)}.ftr-btm{max-width:700px;margin:0 auto;padding:14px 20px 8px;text-align:center;border-top:1px dashed #E0DDD8}.ftr-btm p{margin:0 0 4px;color:var(--muted);font-size:14px}.ftr-btm a{color:var(--green);font-weight:700;text-decoration:none;font-size:15px}
@media(max-width:700px){.page-hero{padding:28px 20px 24px}.page-hero h1{font-size:25px}.p-card{padding:20px 18px}.p-name{font-size:19px}.p-img{width:80px;padding:10px}.p-img svg{width:52px}.r-grid{grid-template-columns:1fr}.ftr-form{flex-direction:column}.ftr-form button{width:100%}.faq-q{font-size:17px;padding:14px 18px}.faq-a{padding:0 18px 14px}}
      `}</style>
<header className="hdr"><div className="hdr-inner"><a href="/" className="hdr-logo"><svg viewBox="0 0 36 36" fill="none"><circle cx="18" cy="18" r="16" fill="#1A5632"/><path d="M18 28 L12.5 21.5 C10 18.5 10 15.5 12.5 13.5 C14.5 12 16.5 13 18 15.5 C19.5 13 21.5 12 23.5 13.5 C26 15.5 26 18.5 23.5 21.5Z" fill="#4ADE80" opacity=".85"/><path d="M13 20.5L16 20.5 17 17.5 18.5 23 20 19.5 23 19.5" fill="none" stroke="#fff" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg><span>VitaTrack</span></a><nav className="hdr-nav"><a href="/">Home</a><a href="/conditions/">Health Conditions</a><a href="/tools/">Health Tools</a></nav><button className="hdr-toggle" aria-label="Menu"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg></button></div></header>
<div id="m" className="mob"><div className="mob-top"><a href="/" className="mob-logo"><svg viewBox="0 0 36 36" fill="none"><circle cx="18" cy="18" r="16" fill="#1A5632"/><path d="M18 28 L12.5 21.5 C10 18.5 10 15.5 12.5 13.5 C14.5 12 16.5 13 18 15.5 C19.5 13 21.5 12 23.5 13.5 C26 15.5 26 18.5 23.5 21.5Z" fill="#4ADE80" opacity=".85"/><path d="M13 20.5L16 20.5 17 17.5 18.5 23 20 19.5 23 19.5" fill="none" stroke="#fff" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"/></svg><span>VitaTrack</span></a><button className="mob-x">✕</button></div><nav className="mob-links"><a href="/">Home</a><a href="/conditions/">Health Conditions</a><a href="/tools/">Health Tools</a><a href="/about/">About Us</a><a href="/contact/">Contact Us</a></nav></div>

<section className="page-hero"><div className="page-hero-inner">
<div className="breadcrumb"><a href="/">← All conditions</a></div>
<h1>6 Best Skin &amp; Hair Supplements for Seniors</h1>
<p>Doctor-reviewed supplements for thinning hair, dry skin, wrinkles, brittle nails, and overall appearance after age 60.</p>
</div></section>

<div className="main-wrap">
<div className="main">

<div className="intro"><h3>A note about these recommendations</h3><p>Skin and hair changes are a natural part of aging — collagen production drops, skin thins, and hair growth slows. These supplements support your body's natural repair processes from the inside out. Results take 8-12 weeks of consistent daily use. Every product below is selected based on clinical evidence.</p></div>

<div className="qp"><h3>⚡ Quick recommendation</h3>
<p><strong>If you try one thing:</strong> <a href="#collagen">#1 Collagen Peptides</a> — the building block of skin, hair, and nails.</p>
<p><strong>For a solid combo:</strong> <a href="#collagen">#1 Collagen</a> + <a href="#vitaminc">#3 Vitamin C</a> + <a href="#ha">#4 Hyaluronic Acid</a></p>
<p><strong>For thinning hair specifically:</strong> <a href="#biotin">#2 Biotin</a> + <a href="#collagen">#1 Collagen</a></p>
</div>

<div className="p-card" id="collagen"><div className="p-num">1</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><path d="M52 78Q56 74 60 78Q64 74 68 78Q64 82 60 78Q56 82 52 78Z" fill="#F5F5DC" opacity=".8"/><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">COLLA</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">GEN I&III</text></svg></div>
<div className="p-info"><h2 className="p-name">Collagen Peptides (Types I & III)</h2><div className="p-sub">The protein your skin and hair are made of — production drops 1% per year after 20</div><div className="p-pills"><span className="p-pill">10g daily</span><span className="p-pill">Any time</span><span className="p-pill">8-12 weeks</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Types I & III are the specific collagens for skin elasticity, hair strength, and nail growth</span></div><div className="p-chk"><span className="tick">✓</span><span>Studies show improved skin hydration and reduced wrinkle depth in 8-12 weeks</span></div><div className="p-chk"><span className="tick">✓</span><span>Hydrolyzed peptides dissolve in coffee, water, or smoothies — no taste</span></div><div className="p-chk"><span className="tick">✓</span><span>Also supports joint cartilage — double benefit for aging bodies</span></div></div>
<div className="p-badges"><span className="p-badge">Types I & III</span><span className="p-badge">Hydrolyzed</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> "Types I & III" hydrolyzed collagen peptides — unflavored powder, grass-fed</div>
<a href="https://amzn.to/4lPcoBA" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $20–30 for a 1-month supply</div></div>

<div className="p-card" id="biotin"><div className="p-num">2</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><text x="60" y="84" textAnchor="middle" fontFamily="sans-serif" fontSize="12" fontWeight="900" fill="#1A5632">B7</text><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="6" fontWeight="700" fill="#1A5632">BIOTIN</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fontWeight="700" fill="#1A5632">5000mcg</text></svg></div>
<div className="p-info"><h2 className="p-name">Biotin (Vitamin B7)</h2><div className="p-sub">The "hair vitamin" — supports keratin production for stronger hair and nails</div><div className="p-pills"><span className="p-pill">5000mcg daily</span><span className="p-pill">With food</span><span className="p-pill">8-12 weeks</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Supports keratin production — the protein that makes up hair, skin, and nails</span></div><div className="p-chk"><span className="tick">✓</span><span>Studies show reduced hair shedding and improved nail thickness in 12 weeks</span></div><div className="p-chk"><span className="tick">✓</span><span>5000mcg is the clinical dose — lower doses may not produce visible results</span></div><div className="p-chk"><span className="tick">✓</span><span>Note: can interfere with thyroid and troponin lab tests — tell your doctor</span></div></div>
<div className="p-badges"><span className="p-badge">5000mcg dose</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> 5000mcg (not 300mcg) — tell your doctor before blood tests</div>
<a href="https://amzn.to/4uNuEiB" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $8–14 for a 4-month supply</div></div>

<div className="p-card" id="vitaminc"><div className="p-num">3</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><text x="60" y="84" textAnchor="middle" fontFamily="sans-serif" fontSize="14" fontWeight="900" fill="#E8960C">C</text><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="6" fontWeight="700" fill="#1A5632">VIT C</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fontWeight="700" fill="#1A5632">1000mg</text></svg></div>
<div className="p-info"><h2 className="p-name">Vitamin C (Buffered)</h2><div className="p-sub">Essential for collagen synthesis — your body cannot make collagen without it</div><div className="p-pills"><span className="p-pill">1000mg daily</span><span className="p-pill">With food</span><span className="p-pill">Ongoing</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Your body literally cannot produce collagen without vitamin C — they're inseparable</span></div><div className="p-chk"><span className="tick">✓</span><span>Also a powerful antioxidant — protects skin cells from UV and environmental damage</span></div><div className="p-chk"><span className="tick">✓</span><span>Buffered form is gentle on sensitive stomachs — no acid reflux</span></div><div className="p-chk"><span className="tick">✓</span><span>Take alongside collagen supplements for maximum skin and hair benefits</span></div></div>
<div className="p-badges"><span className="p-badge">Buffered</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> Buffered Vitamin C — 1000mg, gentle on stomach</div>
<a href="https://amzn.to/3NGECBG" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $10–16 for a 3-month supply</div></div>

<div className="p-card" id="ha"><div className="p-num">4</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><circle cx="60" cy="80" r="7" fill="#85B7EB" opacity=".4"/><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="6" fontWeight="700" fill="#1A5632">HA</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fontWeight="700" fill="#1A5632">150mg</text></svg></div>
<div className="p-info"><h2 className="p-name">Hyaluronic Acid</h2><div className="p-sub">Holds 1,000x its weight in water — the ultimate skin hydrator</div><div className="p-pills"><span className="p-pill">150mg daily</span><span className="p-pill">With water</span><span className="p-pill">6-8 weeks</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Your skin's HA content drops 50% by age 50 — causing dryness and wrinkles</span></div><div className="p-chk"><span className="tick">✓</span><span>Oral HA supplements increase skin moisture measurably in clinical studies</span></div><div className="p-chk"><span className="tick">✓</span><span>Also lubricates joints — bonus benefit for aging knees and hips</span></div><div className="p-chk"><span className="tick">✓</span><span>Works from the inside out — complements topical HA serums</span></div></div>
<div className="p-badges"><span className="p-badge">150mg dose</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> 150mg capsules — drink plenty of water alongside for best results</div>
<a href="https://amzn.to/40LZXNf" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $14–22 for a 2-month supply</div></div>

<div className="p-card" id="vitamine"><div className="p-num">5</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><text x="60" y="84" textAnchor="middle" fontFamily="sans-serif" fontSize="14" fontWeight="900" fill="#4ADE80">E</text><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="6" fontWeight="700" fill="#1A5632">VIT E</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="5" fontWeight="700" fill="#1A5632">400IU</text></svg></div>
<div className="p-info"><h2 className="p-name">Vitamin E (Mixed Tocopherols)</h2><div className="p-sub">Fat-soluble antioxidant that protects skin cell membranes</div><div className="p-pills"><span className="p-pill">400 IU daily</span><span className="p-pill">With food</span><span className="p-pill">Ongoing</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Protects skin cell membranes from UV and oxidative damage</span></div><div className="p-chk"><span className="tick">✓</span><span>Mixed tocopherols (not just alpha) provide the full spectrum of protection</span></div><div className="p-chk"><span className="tick">✓</span><span>Supports skin moisture retention and healing from the inside</span></div><div className="p-chk"><span className="tick">✓</span><span>Works synergistically with Vitamin C — take both for best results</span></div></div>
<div className="p-badges"><span className="p-badge">Mixed tocopherols</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> "Mixed tocopherols" not just "d-alpha tocopherol" — 400 IU softgels</div>
<a href="https://amzn.to/4t8CW3d" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $12–18 for a 3-month supply</div></div>

<div className="p-card" id="epo"><div className="p-num">6</div>
<div className="p-top"><div className="p-img"><svg viewBox="0 0 120 140" fill="none"><rect x="25" y="35" width="70" height="90" rx="8" fill="#1A5632"/><rect x="25" y="35" width="70" height="30" rx="8" fill="#22703F"/><rect x="38" y="18" width="44" height="20" rx="4" fill="#14442A"/><rect x="33" y="72" width="54" height="40" rx="4" fill="white" opacity=".95"/><circle cx="56" cy="80" r="4" fill="#FFD700" opacity=".6"/><circle cx="64" cy="80" r="4" fill="#FFD700" opacity=".4"/><text x="60" y="99" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">EVENING</text><text x="60" y="107" textAnchor="middle" fontFamily="sans-serif" fontSize="4.5" fontWeight="700" fill="#1A5632">PRIMROSE</text></svg></div>
<div className="p-info"><h2 className="p-name">Evening Primrose Oil</h2><div className="p-sub">GLA fatty acid that hydrates dry, flaky skin from the inside</div><div className="p-pills"><span className="p-pill">1000mg daily</span><span className="p-pill">With food</span><span className="p-pill">6-8 weeks</span></div></div></div>
<div className="p-checks"><div className="p-chk"><span className="tick">✓</span><span>Rich in GLA (gamma-linolenic acid) — an omega-6 that reduces skin inflammation</span></div><div className="p-chk"><span className="tick">✓</span><span>Studies show improved skin moisture, elasticity, and reduced dryness</span></div><div className="p-chk"><span className="tick">✓</span><span>Particularly effective for dry, flaky, or eczema-prone skin in seniors</span></div><div className="p-chk"><span className="tick">✓</span><span>Also supports hormonal balance and overall skin health</span></div></div>
<div className="p-badges"><span className="p-badge">Cold-pressed</span><span className="p-badge">Third-party tested</span></div>
<div className="p-tip"><strong>Look for on Amazon:</strong> Cold-pressed, 1000mg softgels, GLA content listed on label</div>
<a href="https://amzn.to/4ssUV49" className="p-btn" target="_blank" rel="noopener noreferrer nofollow">Check Price on Amazon <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M7 17l10-10"/><path d="M7 7h10v10"/></svg></a>
<div className="p-price">Typically $12–18 for a 2-month supply</div></div>

<div className="faq"><h2>Frequently Asked Questions</h2>
<div className="faq-item"><button className="faq-q">What is the best supplement for aging skin?<span className="faq-icon">+</span></button><div className="faq-a">Collagen Peptides (Types I & III) are the most effective — studies show improved skin hydration and reduced wrinkles in 8-12 weeks. Pair with Vitamin C which your body needs to produce collagen. Hyaluronic Acid adds moisture from within.</div></div>
<div className="faq-item"><button className="faq-q">Can supplements help with thinning hair?<span className="faq-icon">+</span></button><div className="faq-a">Biotin (5000mcg) supports keratin production and can reduce hair shedding. Collagen provides amino acids for hair structure. Results take 8-12 weeks. Note: biotin can affect thyroid lab tests — tell your doctor.</div></div>
<div className="faq-item"><button className="faq-q">Does collagen actually work when taken orally?<span className="faq-icon">+</span></button><div className="faq-a">Yes — hydrolyzed collagen peptides are broken down small enough to absorb into your bloodstream. Multiple clinical studies show measurable improvements in skin elasticity, hydration, and wrinkle depth after 8-12 weeks of daily 10g intake.</div></div>
<div className="faq-item"><button className="faq-q">How long do skin supplements take to work?<span className="faq-icon">+</span></button><div className="faq-a">Most skin supplements need 8-12 weeks. Collagen: 8-12 weeks for visible improvement. Hyaluronic Acid: 6-8 weeks for hydration. Biotin: 8-12 weeks for hair and nails. Your skin renews every 28 days, so give it at least 2-3 cycles.</div></div>
</div>

<div className="related"><h3>Related Health Conditions</h3><div className="r-grid">
<a href="/longevity/" className="r-link"><span>🧬</span> Longevity</a>
<a href="/conditions/osteoarthritis" className="r-link"><span>🦴</span> Joints &amp; bones</a>
<a href="/conditions/macular-degeneration-amd" className="r-link"><span>👁️</span> Eyes &amp; vision</a>
<a href="/digestion/" className="r-link"><span>🍃</span> Digestion &amp; gut</a>
</div></div>

<div className="disc"><h4>Medical &amp; Affiliate Disclosure</h4>
<p>This page is for educational purposes only. Results vary based on individual factors. Always consult your doctor before starting any supplement.</p>
<p>VitaTrack may earn a commission from purchases through links on this page.</p></div>

</div>

<aside className="sidebar"><div className="sidebar-inner">
<h4>Quick navigation</h4>
<div className="sb-links">
<a href="#collagen" className="sb-link"><span className="sb-num">1</span><span className="sb-name">Collagen I&III</span></a>
<a href="#biotin" className="sb-link"><span className="sb-num">2</span><span className="sb-name">Biotin</span></a>
<a href="#vitaminc" className="sb-link"><span className="sb-num">3</span><span className="sb-name">Vitamin C</span></a>
<a href="#ha" className="sb-link"><span className="sb-num">4</span><span className="sb-name">Hyaluronic Acid</span></a>
<a href="#vitamine" className="sb-link"><span className="sb-num">5</span><span className="sb-name">Vitamin E</span></a>
<a href="#epo" className="sb-link"><span className="sb-num">6</span><span className="sb-name">Evening Primrose</span></a>
</div>
<hr className="sb-divider" />
<a href="#collagen" className="sb-cta">See #1 Pick →</a>
</div></aside>
</div>

<footer className="ftr"><div className="ftr-inner"><div className="ftr-brand"><a href="/" className="ftr-logo"><svg viewBox="0 0 28 28" fill="none"><circle cx="14" cy="14" r="13" fill="#1A5632" opacity=".14"/><path d="M7 16.5l4 4L21 9.5" fill="none" stroke="#1A5632" strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round"/></svg><span>TheVitatrack</span></a><ul className="ftr-social"><li><a href="https://www.facebook.com/profile.php?id=61550903702285" target="_blank" aria-label="Facebook"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M22 12.07C22 6.48 17.52 2 11.93 2S2 6.48 2 12.07c0 5 3.66 9.14 8.44 9.93v-7.03H8.08v-2.9h2.36V9.41c0-2.33 1.38-3.62 3.5-3.62.99 0 2.02.18 2.02.18v2.23h-1.14c-1.12 0-1.47.7-1.47 1.42v1.7h2.5l-.4 2.9h-2.1V22c4.78-.79 8.44-4.93 8.44-9.93z"/></svg></a></li><li><a href="https://www.youtube.com/@healthyhabitat1304" target="_blank" aria-label="YouTube"><svg viewBox="0 0 24 24"><path fill="currentColor" d="M23.5 6.2a3.1 3.1 0 0 0-2.2-2.2C19.3 3.5 12 3.5 12 3.5s-7.3 0-9.3.5A3.1 3.1 0 0 0 .5 6.2C0 8.3 0 12 0 12s0 3.7.5 5.8a3.1 3.1 0 0 0 2.2 2.2c2 .5 9.3.5 9.3.5s7.3 0 9.3-.5a3.1 3.1 0 0 0 2.2-2.2c.5-2.1.5-5.8.5-5.8s0-3.7-.5-5.8zM9.6 15.6V8.4L15.8 12l-6.2 3.6z"/></svg></a></li></ul></div>
<div className="ftr-news"><h4>Get our wellness newsletter</h4><form className="ftr-form" action="/subscribe" method="post"><input name="email" type="email" placeholder="Enter your email" required /><button type="submit">SIGN UP</button></form><p className="ftr-priv">Your <a href="/privacy-policy/">privacy</a> is important to us</p></div>
<ul className="ftr-links"><li><a href="/about/">About Us</a></li><li><a href="/contact/">Contact Us</a></li><li><a href="/privacy-policy/">Privacy Policy</a></li><li><a href="/terms-of-use/">Terms of Use</a></li><li><a href="/sitemap/">Sitemap</a></li><li><a href="/conditions/">Health Conditions</a></li><li><a href="/tools/">Health Tools</a></li></ul>
</div><div className="ftr-btm"><p>&copy; 2026 TheVitatrack. Educational content only &mdash; not a substitute for professional advice.</p><p>As an Amazon Associate, VitaTrack earns from qualifying purchases.</p></div></footer>

      <section style={{maxWidth:"840px",margin:"48px auto 60px",padding:"0 20px"}}>
        <div style={{borderTop:"2px solid #E8E6E1",paddingTop:"32px"}}>
          <h2 style={{color:"#14442A",fontSize:"1.4rem",fontWeight:700,marginBottom:"20px",fontFamily:"Fraunces, serif"}}>Related Health Guides</h2>
          <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))",gap:"4px"}}>
          <Link href="/conditions/wounds-skin-tears" className="interlink">Wounds & Skin Tears</Link>
          <Link href="/conditions/dry-eyes" className="interlink">Dry Eyes</Link>
          <Link href="/conditions/vitamin-d-calcium-basics" className="interlink">Vitamin D & Calcium</Link>
          <Link href="/conditions/malnutrition-unintended-weight-loss" className="interlink">Malnutrition & Weight Loss</Link>
          <Link href="/conditions/diabetes-type-2" className="interlink">Type 2 Diabetes</Link>
          </div>
        </div>
      </section>
    </>
  );
}
